spring:
  application:
    name: gateway-server
  profiles:
    active:
    - dev

    
zuul:
  
  routes:
    users: 
      path: /users/**
      serviceId: user-service
      strip-prefix: false
      url: https://7i6rudc3m2.execute-api.us-east-1.amazonaws.com/uat
    checkins:
      path: /checkins/**
      serviceId: checkin-service
      strip-prefix: false
      url: https://7i6rudc3m2.execute-api.us-east-1.amazonaws.com/uat
    cohorts:
      path: /cohorts/**
      serviceId: user-service
      strip-prefix: false
      url: https://7i6rudc3m2.execute-api.us-east-1.amazonaws.com/uat
    interviews:
      path: /interviews/**
      serviceId: interview-service
      url: http://localhost:8091
    
    cognito:
      path: /cognito/**
      url: https://t4o3pxu8dj.execute-api.us-west-2.amazonaws.com/dev
      strip-prefix: false
    
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/
    eureka-server-read-timeout-seconds: 100
  
ribbon:
  eureka:
    enabled: true
  ReadTimeout: 60000
  ConnectTimeout: 100000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 900000


  
server:
  port: 8765


  
