spring:
  application:
    name: gateway-server

    
zuul:
  routes:
    users: 
      path: /user-service/**
      url: http://localhost:8090/
    cognito:
      path: /cognito/**
      url: https://7i6rudc3m2.execute-api.us-east-1.amazonaws.com/uat/
      strip-prefix: false
  sensitive-headers:
  
server:
  port: 8765



  
